In [1]:
num_of_lines=2000

In [2]:
import pandas as pd
import numpy as np
dataset=pd.read_excel("C:/Users/97254/Downloads/patient_level__ver 12_proj1_sn_5-13.xlsx", engine='openpyxl')
print(dataset.shape)

(1020, 70)

In [3]:
dataset = dataset[~dataset['age'].isin(['NAN'])]

In [4]:
dataset.head()

,ser_num,ICU_LOS,LOS_Group,ICU_mortality,HOSP_mortality,28_mortality,90 days mortality,trauma,metabolic,gastrointestinal,...,EN_pro_day12,PN_pro_day12,EN_pro_day13,PN_pro_day13,EN_pro_day0/kg,EN_pro_day1/kg,EN_pro_day2/kg,EN_pro_day3/kg,EN_pro_day4/kg,EN_pro_day5/kg
0,2,9,LOS_8-13,0,0,0,0,0,1,0,...,0.0,0.000000,0.0,0.0,1.250297,1.221456,1.578462,0.995015,1.394308,1.403077
1,3,5,LOS_5-7,0,0,0,0,0,1,0,...,0.0,0.000000,0.0,0.0,0.758495,0.000000,0.670993,1.177788,0.403229,0.000000
2,5,13,LOS_8-13,0,0,0,0,0,0,1,...,0.0,53.273355,0.0,0.0,0.000000,0.000000,0.023259,1.396370,0.256457,0.000000
3,7,6,LOS_5-7,0,0,0,0,0,1,1,...,0.0,0.000000,0.0,0.0,1.145278,1.520000,1.520000,1.520000,1.520000,1.209667
4,9,9,LOS_8-13,0,0,0,0,1,1,1,...,0.0,0.000000,0.0,0.0,0.014902,0.858353,0.731984,0.922729,1.287529,1.287529

In [5]:
dataset.shape

(976, 70)

In [6]:
target = dataset[['ICU_mortality']]
dataset=dataset.drop(['28_mortality'], axis=1)
dataset=dataset.drop(['HOSP_mortality'], axis=1)
dataset=dataset.drop(['90 days mortality'], axis=1)
dataset=dataset.drop(['ICU_mortality'], axis=1)
dataset=dataset.drop(['ICU_LOS'], axis=1)
dataset.head()

,ser_num,LOS_Group,trauma,metabolic,gastrointestinal,Sepsis,age,gender,weight,BMI,...,EN_pro_day12,PN_pro_day12,EN_pro_day13,PN_pro_day13,EN_pro_day0/kg,EN_pro_day1/kg,EN_pro_day2/kg,EN_pro_day3/kg,EN_pro_day4/kg,EN_pro_day5/kg
0,2,LOS_8-13,0,1,0,1,72,F,65.0,23.875115,...,0.0,0.000000,0.0,0.0,1.250297,1.221456,1.578462,0.995015,1.394308,1.403077
1,3,LOS_5-7,0,1,0,1,58,M,101.0,32.979592,...,0.0,0.000000,0.0,0.0,0.758495,0.000000,0.670993,1.177788,0.403229,0.000000
2,5,LOS_8-13,0,0,1,1,44,M,70.0,22.857143,...,0.0,53.273355,0.0,0.0,0.000000,0.000000,0.023259,1.396370,0.256457,0.000000
3,7,LOS_5-7,0,1,1,0,71,F,48.0,19.227688,...,0.0,0.000000,0.0,0.0,1.145278,1.520000,1.520000,1.520000,1.520000,1.209667
4,9,LOS_8-13,1,1,1,0,60,F,85.0,32.791945,...,0.0,0.000000,0.0,0.0,0.014902,0.858353,0.731984,0.922729,1.287529,1.287529

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['active problems'] = le.fit_transform(dataset['active problems'].astype(str))
dataset['background problems'] = le.fit_transform(dataset['background problems'].astype(str))
dataset['gender'] = le.fit_transform(dataset['gender'].astype(str))
dataset['feeding'] = le.fit_transform(dataset['feeding'].astype(str))
dataset['LOS_Group'] = le.fit_transform(dataset['feeding'].astype(str))

dataset.head()

,ser_num,LOS_Group,trauma,metabolic,gastrointestinal,Sepsis,age,gender,weight,BMI,...,EN_pro_day12,PN_pro_day12,EN_pro_day13,PN_pro_day13,EN_pro_day0/kg,EN_pro_day1/kg,EN_pro_day2/kg,EN_pro_day3/kg,EN_pro_day4/kg,EN_pro_day5/kg
0,2,0,0,1,0,1,72,0,65.0,23.875115,...,0.0,0.000000,0.0,0.0,1.250297,1.221456,1.578462,0.995015,1.394308,1.403077
1,3,0,0,1,0,1,58,1,101.0,32.979592,...,0.0,0.000000,0.0,0.0,0.758495,0.000000,0.670993,1.177788,0.403229,0.000000
2,5,1,0,0,1,1,44,1,70.0,22.857143,...,0.0,53.273355,0.0,0.0,0.000000,0.000000,0.023259,1.396370,0.256457,0.000000
3,7,0,0,1,1,0,71,0,48.0,19.227688,...,0.0,0.000000,0.0,0.0,1.145278,1.520000,1.520000,1.520000,1.520000,1.209667
4,9,0,1,1,1,0,60,0,85.0,32.791945,...,0.0,0.000000,0.0,0.0,0.014902,0.858353,0.731984,0.922729,1.287529,1.287529

In [8]:
dataset.shape

(976, 65)

In [9]:

from sklearn.model_selection import train_test_split
#this function randomly split the data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(dataset, target, test_size=.2)
#test_size=.3 means that our test set will be 30% of the train set.
x_train.head()

,ser_num,LOS_Group,trauma,metabolic,gastrointestinal,Sepsis,age,gender,weight,BMI,...,EN_pro_day12,PN_pro_day12,EN_pro_day13,PN_pro_day13,EN_pro_day0/kg,EN_pro_day1/kg,EN_pro_day2/kg,EN_pro_day3/kg,EN_pro_day4/kg,EN_pro_day5/kg
135,353,0,1,1,0,1,55,1,94.0,30.693878,...,0.0,0.0,0.0,0.0,0.089475,0.385929,0.266990,0.043660,0.198894,0.288369
627,1566,0,0,0,0,1,35,1,70.0,20.452885,...,0.0,0.0,0.0,0.0,0.970026,0.322107,0.641352,0.905143,0.867429,0.019486
1019,2526,0,0,1,0,1,69,1,110.0,35.918367,...,0.0,0.0,0.0,0.0,0.572800,1.133164,1.368545,0.718961,1.334745,0.825952
145,386,0,1,1,0,1,84,0,110.0,42.968750,...,0.0,0.0,0.0,0.0,0.212800,0.310667,0.380800,0.384000,0.145600,0.000000
269,684,0,1,1,1,0,36,1,90.0,26.296567,...,0.0,0.0,0.0,0.0,0.287467,0.555867,0.704000,0.682978,0.592044,0.000000

# DecisionTreeClassifier

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(x_train, y_train)  #train parameters: features and target
pred = dtree.predict(x_test)  #parameter: new data to predict

In [11]:
from sklearn.metrics import accuracy_score,recall_score
accuracy_score(y_test, pred)
#parameters: targets to be predicted and predictions from new data used before

0.6938775510204082

In [12]:
dtree = DecisionTreeClassifier(criterion='gini')
dtree.fit(x_train, y_train)
pred = dtree.predict(x_test)
print('Criterion=gini', recall_score(y_test, pred))
dtree = DecisionTreeClassifier(criterion='entropy')
dtree.fit(x_train, y_train)
pred = dtree.predict(x_test)
print('Criterion=entropy', recall_score(y_test, pred))

Criterion=gini 0.39655172413793105
Criterion=entropy 0.43103448275862066

explore by depth

In [13]:
max_depth = []
acc_gini = []
acc_entropy = []
for i in range(1,20):
 dtree = DecisionTreeClassifier(criterion='gini', max_depth=i)
 dtree.fit(x_train, y_train)
 pred = dtree.predict(x_test)
 acc_gini.append(recall_score(y_test, pred))
 ####
 dtree = DecisionTreeClassifier(criterion='entropy', max_depth=i)
 dtree.fit(x_train, y_train)
 pred = dtree.predict(x_test)
 acc_entropy.append(recall_score(y_test, pred))
 ####
 max_depth.append(i)
d = pd.DataFrame({'acc_gini':pd.Series(acc_gini), 
 'acc_entropy':pd.Series(acc_entropy),
 'max_depth':pd.Series(max_depth)})
# visualizing changes in parameters

In [14]:
d.head(20)

    acc_gini  acc_entropy  max_depth
0   0.172414     0.172414          1
1   0.258621     0.017241          2
2   0.241379     0.241379          3
3   0.258621     0.275862          4
4   0.258621     0.155172          5
5   0.327586     0.275862          6
6   0.344828     0.275862          7
7   0.293103     0.224138          8
8   0.327586     0.206897          9
9   0.344828     0.189655         10
10  0.379310     0.275862         11
11  0.396552     0.275862         12
12  0.396552     0.327586         13
13  0.327586     0.396552         14
14  0.431034     0.344828         15
15  0.482759     0.396552         16
16  0.413793     0.362069         17
17  0.344828     0.396552         18
18  0.448276     0.362069         19

In [16]:
dtree = DecisionTreeClassifier(criterion='gini', max_depth=16)
dtree.fit(x_train, y_train)
pred = dtree.predict(x_test)
recall_score(y_test, pred)
#Accuracy: 0.814

0.41379310344827586

In [34]:
x_train.iloc[:,6].head()

135     55
627     35
1019    69
145     84
269     36
Name: age, dtype: object

In [17]:
#PN_pro_day7 PN_pro_day9 APACHEII pro_to_target_day0 age EN_pro_day1 active problems
from sklearn import tree
print(tree.export_text(dtree))

|--- feature_46 <= 29.55
|   |--- feature_10 <= 26.50
|   |   |--- feature_6 <= 53.50
|   |   |   |--- feature_10 <= 24.50
|   |   |   |   |--- feature_33 <= 55.21
|   |   |   |   |   |--- feature_61 <= 1.35
|   |   |   |   |   |   |--- feature_19 <= 1.37
|   |   |   |   |   |   |   |--- feature_25 <= 1.53
|   |   |   |   |   |   |   |   |--- feature_16 <= 0.36
|   |   |   |   |   |   |   |   |   |--- feature_47 <= 0.14
|   |   |   |   |   |   |   |   |   |   |--- feature_12 <= 11.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_12 >  11.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_47 >  0.14
|   |   |   |   |   |   |   |   |   |   |--- feature_23 <= 0.21
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_23 >  0.21
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |--- feature_16 >  0.36
|   |   |   |   |   |   |   |   |   |--- feature_19 <= 0.53
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_19 >  0.53
|   |   |   |   |   |   |   |   |   |   |--- feature_16 <= 0.39
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_16 >  0.39
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_25 >  1.53
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_19 >  1.37
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_61 >  1.35
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_33 >  55.21
|   |   |   |   |   |--- feature_59 <= 0.92
|   |   |   |   |   |   |--- feature_8 <= 55.00
|   |   |   |   |   |   |   |--- feature_31 <= 26.22
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_31 >  26.22
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_8 >  55.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_59 >  0.92
|   |   |   |   |   |   |--- feature_60 <= 1.00
|   |   |   |   |   |   |   |--- feature_29 <= 314.31
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_29 >  314.31
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_60 >  1.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_10 >  24.50
|   |   |   |   |--- class: 1
|   |   |--- feature_6 >  53.50
|   |   |   |--- feature_11 <= 2.00
|   |   |   |   |--- feature_44 <= 60.32
|   |   |   |   |   |--- feature_0 <= 2133.00
|   |   |   |   |   |   |--- feature_21 <= 1.42
|   |   |   |   |   |   |   |--- feature_17 <= 1.96
|   |   |   |   |   |   |   |   |--- feature_45 <= 132.78
|   |   |   |   |   |   |   |   |   |--- feature_9 <= 50.72
|   |   |   |   |   |   |   |   |   |   |--- feature_59 <= 1.16
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6
|   |   |   |   |   |   |   |   |   |   |--- feature_59 >  1.16
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |--- feature_9 >  50.72
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_45 >  132.78
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_17 >  1.96
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_21 >  1.42
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_0 >  2133.00
|   |   |   |   |   |   |--- feature_6 <= 83.50
|   |   |   |   |   |   |   |--- feature_39 <= 110.52
|   |   |   |   |   |   |   |   |--- feature_34 <= 56.95
|   |   |   |   |   |   |   |   |   |--- feature_33 <= 75.28
|   |   |   |   |   |   |   |   |   |   |--- feature_38 <= 95.95
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- feature_38 >  95.95
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_33 >  75.28
|   |   |   |   |   |   |   |   |   |   |--- feature_17 <= 0.62
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_17 >  0.62
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- feature_34 >  56.95
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_39 >  110.52
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_6 >  83.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_44 >  60.32
|   |   |   |   |   |--- class: 1
|   |   |   |--- feature_11 >  2.00
|   |   |   |   |--- feature_15 <= 0.47
|   |   |   |   |   |--- feature_62 <= 0.73
|   |   |   |   |   |   |--- feature_26 <= 0.17
|   |   |   |   |   |   |   |--- feature_12 <= 8.50
|   |   |   |   |   |   |   |   |--- feature_61 <= 0.47
|   |   |   |   |   |   |   |   |   |--- feature_62 <= 0.05
|   |   |   |   |   |   |   |   |   |   |--- feature_6 <= 79.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- feature_6 >  79.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_62 >  0.05
|   |   |   |   |   |   |   |   |   |   |--- feature_63 <= 0.21
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_63 >  0.21
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |--- feature_61 >  0.47
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_12 >  8.50
|   |   |   |   |   |   |   |   |--- feature_3 <= 0.50
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_3 >  0.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_26 >  0.17
|   |   |   |   |   |   |   |--- feature_55 <= 49.27
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_55 >  49.27
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_62 >  0.73
|   |   |   |   |   |   |--- feature_16 <= 0.19
|   |   |   |   |   |   |   |--- feature_18 <= 0.60
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_18 >  0.60
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_16 >  0.19
|   |   |   |   |   |   |   |--- feature_51 <= 46.08
|   |   |   |   |   |   |   |   |--- feature_41 <= 6.60
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_41 >  6.60
|   |   |   |   |   |   |   |   |   |--- feature_9 <= 29.39
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_9 >  29.39
|   |   |   |   |   |   |   |   |   |   |--- feature_2 <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_2 >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_51 >  46.08
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_15 >  0.47
|   |   |   |   |   |--- feature_29 <= 174.80
|   |   |   |   |   |   |--- feature_16 <= 0.70
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_16 >  0.70
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_29 >  174.80
|   |   |   |   |   |   |--- feature_54 <= 5.14
|   |   |   |   |   |   |   |--- feature_12 <= 7.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 557.00
|   |   |   |   |   |   |   |   |   |--- feature_41 <= 62.37
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_41 >  62.37
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_0 >  557.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_12 >  7.50
|   |   |   |   |   |   |   |   |--- feature_22 <= 0.01
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_22 >  0.01
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_54 >  5.14
|   |   |   |   |   |   |   |--- class: 1
|   |--- feature_10 >  26.50
|   |   |--- feature_0 <= 296.50
|   |   |   |--- feature_19 <= 0.74
|   |   |   |   |--- feature_35 <= 82.21
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_35 >  82.21
|   |   |   |   |   |--- class: 1
|   |   |   |--- feature_19 >  0.74
|   |   |   |   |--- class: 1
|   |   |--- feature_0 >  296.50
|   |   |   |--- feature_62 <= 1.24
|   |   |   |   |--- feature_17 <= 0.22
|   |   |   |   |   |--- feature_15 <= 0.27
|   |   |   |   |   |   |--- feature_9 <= 36.69
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_9 >  36.69
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_15 >  0.27
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_17 >  0.22
|   |   |   |   |   |--- feature_16 <= 1.09
|   |   |   |   |   |   |--- feature_10 <= 28.50
|   |   |   |   |   |   |   |--- feature_11 <= 2.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_11 >  2.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_10 >  28.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_16 >  1.09
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_62 >  1.24
|   |   |   |   |--- class: 0
|--- feature_46 >  29.55
|   |--- feature_50 <= 90.00
|   |   |--- feature_16 <= 1.03
|   |   |   |--- feature_23 <= 0.76
|   |   |   |   |--- feature_6 <= 49.00
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_6 >  49.00
|   |   |   |   |   |--- feature_10 <= 19.50
|   |   |   |   |   |   |--- feature_6 <= 79.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_6 >  79.50
|   |   |   |   |   |   |   |--- feature_23 <= 0.17
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_23 >  0.17
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_10 >  19.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_23 >  0.76
|   |   |   |   |--- class: 1
|   |   |--- feature_16 >  1.03
|   |   |   |--- feature_40 <= 86.65
|   |   |   |   |--- class: 0
|   |   |   |--- feature_40 >  86.65
|   |   |   |   |--- class: 1
|   |--- feature_50 >  90.00
|   |   |--- class: 0

In [ ]:
#PN_pro_day7 PN_pro_day9 APACHEII pro_to_target_day0 age EN_pro_day1 active problems

# RandomForestClassifier

In [19]:
	
from sklearn.ensemble import RandomForestClassifier

In [20]:
clf_4 = RandomForestClassifier(criterion='gini', max_depth=16)
clf_4.fit(x_train, y_train)
 #x_train, x_test, y_train, y_test
# Predict on training set
pred_y_4 = clf_4.predict(x_test)
 
# Is our model still predicting just one class?
print( np.unique( pred_y_4 ) )
# [0 1]
 
# How's our accuracy?
print( recall_score(y_test, pred_y_4) )
# 0.9744

<ipython-input-20-a46f23cc5096>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf_4.fit(x_train, y_train)

[0 1]
0.06521739130434782